-- Customer orders for in-app purchases

create extension if not exists "pgcrypto";

create table if not exists public.customer_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  user_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'confirmed',
  total_amount numeric(12, 2) not null,
  currency_code text not null default 'ILS',
  item_count integer not null default 0,
  created_at timestamptz not null default now(),
  constraint customer_orders_status_check check (status in ('confirmed', 'processing', 'cancelled'))
);

create index if not exists customer_orders_user_created_at_idx
  on public.customer_orders (user_id, created_at desc);

create table if not exists public.customer_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.customer_orders(id) on delete cascade,
  product_id text not null,
  product_handle text not null,
  product_title text not null,
  image_url text null,
  unit_price numeric(12, 2) not null,
  quantity integer not null,
  line_total numeric(12, 2) not null,
  created_at timestamptz not null default now()
);

create index if not exists customer_order_items_order_id_idx
  on public.customer_order_items (order_id);

create or replace function public.ensure_customer_order_customer()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.users
    where id = new.user_id
      and role = 'customer'
  ) then
    raise exception 'customer orders can only be created for customer users';
  end if;

  return new;
end;
$$;

drop trigger if exists customer_orders_customer_guard on public.customer_orders;
create trigger customer_orders_customer_guard
before insert or update on public.customer_orders
for each row
execute function public.ensure_customer_order_customer();

alter table public.customer_orders enable row level security;
alter table public.customer_order_items enable row level security;

-- NOTE:
-- This project currently does not use Supabase Auth/JWT sessions, so policies cannot
-- be scoped to auth.uid() yet. The app must always read/write by the logged-in user id.
drop policy if exists "customer_orders_select_any" on public.customer_orders;
create policy "customer_orders_select_any" on public.customer_orders
  for select
  using (true);

drop policy if exists "customer_orders_insert_any" on public.customer_orders;
create policy "customer_orders_insert_any" on public.customer_orders
  for insert
  with check (true);

drop policy if exists "customer_orders_update_any" on public.customer_orders;
create policy "customer_orders_update_any" on public.customer_orders
  for update
  using (true)
  with check (true);

drop policy if exists "customer_orders_delete_any" on public.customer_orders;
create policy "customer_orders_delete_any" on public.customer_orders
  for delete
  using (true);

drop policy if exists "customer_order_items_select_any" on public.customer_order_items;
create policy "customer_order_items_select_any" on public.customer_order_items
  for select
  using (true);

drop policy if exists "customer_order_items_insert_any" on public.customer_order_items;
create policy "customer_order_items_insert_any" on public.customer_order_items
  for insert
  with check (true);

drop policy if exists "customer_order_items_update_any" on public.customer_order_items;
create policy "customer_order_items_update_any" on public.customer_order_items
  for update
  using (true)
  with check (true);

drop policy if exists "customer_order_items_delete_any" on public.customer_order_items;
create policy "customer_order_items_delete_any" on public.customer_order_items
  for delete
  using (true);
